players:
  enableFriendlyDamage: true
regions:

  #Capture Mode defines how the ownership of ControlPoints affects the influence rate.
  #   0 (Default) - Influence Rate is determined by majority controller minus the 2nd majority controller
  #   1 - Influence Rate is determined by majority controller minus all other factions control.
  captureMode: 0
hooks:
  spout: 
    enabled: true
  dynmap:
    enabled: true
  heroes:
    enabled: false
    baseExperience:
      largeBaseCapture: 1000
      smallBaseCapture: 500
      largeBaseDefense: 500
      smallBaseDefense: 250
      controlPointCapture: 50
      enemyPlayerKill: 250
      friendlyPlayerKill: -100
    experienceModifier: 1.0
    groupExperienceModifiers:   #Added to experience Modifier
      default: 0
      members: 0.5