factions:
  faction1:
    displayname: The Elder Tyrants
    permissiongroup: admin
    default: true
    defaultspawn:
      world: exampleregion
    color: red
    factionIcon: "faction.png"
  faction2:
    displayname: Isuren Forces
    permissiongroup: admin2
    default: false
    defaultspawn:
      world: exampleregion2
    color: blue
    factionIcon: "faction2.png"
worlds:
  world:
    regions:
      exampleregion:
        world: world
        displayname: Mekka Valley
        baseinfluence: 300
        adjacentregions:
        - exampleregion2
        controlpoints:
          a:
            x: 179
            y: 64
            z: 62
            captureradius: 5
            baseinfluence: 10
          b:
            x: 172
            y: 64
            z: 36
            captureradius: 5
            baseinfluence: 10
          c:
            x: 159
            y: 64
            z: 56
            captureradius: 5
            baseinfluence: 10
        spawnpoint:
          x: 172
          y: 64
          z: 51
      exampleregion2:
        world: world
        displayname: Ishura Highlands
        baseinfluence: 300
        adjacentregions:
        - exampleregion
        controlpoints:
          a:
            x: 135
            y: 100
            z: 224
            captureradius: 10
            baseinfluence: 10
          b:
            x: 192
            y: 100
            z: 224
            captureradius: 10
            baseinfluence: 10
          c:
            x: 225
            y: 100
            z: 98
            captureradius: 10
            baseinfluence: 10
        spawnpoint:
          x: 177
          y: 64
          z: 29
spout:
  enabled: true
  maxspawnpoints: 10
