factions:
  elderTyrants:
    displayname: The Elder Tyrants
    permissiongroup: elderTyrants
    default: true
    defaultspawn:
      world: elderTyrantsNetherGate
    color: red
    factionIcon: faction.png
  relkanaForces:
    displayname: Relkana Forces
    permissiongroup: relkanaForces
    default: false
    defaultspawn:
      world: relkanaForcesNetherGate
    color: blue
    factionIcon: faction2.png
worlds:
  world:
    regions:
      elderTyrantsNetherGate:
        displayname: The Elder Tyrants Nether Gate
        baseinfluence: 3000
        adjacentregions:
        - torasaurPlains
        - norakDesert
        - mekkaLake
        spawnRegion: true
        spawnpoint:
          x: 291
          y: 67
          z: 294
      relkanaForcesNetherGate:
        displayname: Relkana Forces Nether Gate
        baseinfluence: 3000
        adjacentregions:
        - mekkaLake
        - kurrishSludgeMine
        - ishuraHighlands
        spawnRegion: true
        spawnpoint:
          x: -187
          y: 65
          z: -186
      ishuraHighlands:
        displayname: Ishura Highlands
        baseinfluence: 300
        adjacentregions:
        - relkanaForcesNetherGate
        - mekkaValley
        controlpoints:
          a:
            x: -142
            y: 76
            z: -14
            captureradius: 5
            baseinfluence: 10
        spawnpoint:
          x: -195
          y: 69
          z: -18
      mekkaValley:
        displayname: Mekka Valley
        baseinfluence: 500
        adjacentregions:
        - ishuraHighlands
        - torasaurPlains
        controlpoints:
          a:
            x: -58
            y: 65
            z: 290
            captureradius: 5
            baseinfluence: 10
          b:
            x: -47
            y: 65
            z: 223
            captureradius: 5
            baseinfluence: 10
          c:
            x: -126
            y: 65
            z: 224
            captureradius: 5
            baseinfluence: 10
        spawnpoint:
          x: -116
          y: 65
          z: 267
      torasaurPlains:
        displayname: Torasaur Plains
        baseinfluence: 300
        adjacentregions:
        - elderTyrantsNetherGate
        - mekkaValley
        controlpoints:
          a:
            x: 119
            y: 67
            z: 300
            captureradius: 5
            baseinfluence: 10
        spawnpoint:
          x: 129
          y: 67
          z: 268
      norakDesert:
        displayname: Norak Desert
        baseinfluence: 500
        adjacentregions:
        - elderTyrantsNetherGate
        - twilightForest
        controlpoints:
          a:
            x: 243
            y: 75
            z: 80
            captureradius: 5
            baseinfluence: 10
          b:
            x: 241
            y: 71
            z: 18
            captureradius: 5
            baseinfluence: 10
          c:
            x: 304
            y: 77
            z: -3
            captureradius: 5
            baseinfluence: 10
        spawnpoint:
          x: 280
          y: 65
          z: 22
      twilightForest:
        displayname: Twilight Forest
        baseinfluence: 300
        adjacentregions:
        - norakDesert
        - kurrishSludgeMine
        controlpoints:
          a:
            x: 288
            y: 65
            z: -163
            captureradius: 5
            baseinfluence: 10
        spawnpoint:
          x: 312
          y: 65
          z: -156
      kurrishSludgeMine:
        displayname: Kurrish Sludge Mine
        baseinfluence: 300
        adjacentregions:
        - twilightForest
        - relkanaForcesNetherGate
        controlpoints:
          a:
            x: 97
            y: 65
            z: -153
            captureradius: 5
            baseinfluence: 10
        spawnpoint:
          x: 111
          y: 65
          z: -184
      mekkaLake:
        displayname: Mekka Lake
        baseinfluence: 750
        adjacentregions:
        - elderTyrantsNetherGate
        - relkanaForcesNetherGate
        controlpoints:
          a:
            x: 122
            y: 65
            z: 137
            captureradius: 5
            baseinfluence: 10
          b:
            x: 160
            y: 65
            z: 33
            captureradius: 5
            baseinfluence: 10
          c:
            x: 28
            y: 65
            z: -42
            captureradius: 5
            baseinfluence: 10
          d:
            x: -1
            y: 65
            z: 40
            captureradius: 5
            baseinfluence: 10
        spawnpoint:
          x: 150
          y: 68
          z: -28
spout:
  enabled: true
  maxspawnpoints: 10
