#Available Colors For Factions
#black,blue,brown,cyan,gray,green,light_blue,lime,magenta,orange,pink,purple,red,silver,white,yellow

factions:
  faction1:
    displayname: 'The Elder Tyrants'
    permissiongroup: admin
    default: true
    defaultspawn:
      world: exampleregion
    color: red

worlds:
  world:
    regions:
      exampleregion:
        world: world
        displayname: 'Example Region Name'
        baseinfluence: 300
        adjacentregions:
         - exampleregion2
        controlpoints:
          a:
            x: 135
            y: 45
            z: 224
            captureradius: 10
            baseinfluence: 10
          b:
            x: 192
            y: 23
            z: 224
            captureradius: 10
            baseinfluence: 10
          c:
            x: 225
            y: 42
            z: 98
            captureradius: 10
            baseinfluence: 10
        spawnpoint:
          x: 177
          y: 64
          z: 29

      exampleregion2:
        world: world
        displayname: 'Example Region Number 2'
        baseinfluence: 300
        adjacentregions:
         - exampleregion
        controlpoints:
          a:
            x: 135
            y: 45
            z: 224
            captureradius: 10
            baseinfluence: 10
          b:
            x: 192
            y: 23
            z: 224
            captureradius: 10
            baseinfluence: 10
          c:
            x: 225
            y: 42
            z: 98
            captureradius: 10
            baseinfluence: 10
        spawnpoint:
          x: 177
          y: 64
          z: 29

spout:
  enabled: true
  maxspawnpoints: 10