name: RegionControl
version: "0.7-D6"
description: Utilises WorldGuard Regions to create a Capture-the-Region gamemode.
author: Jhett12321
website: http://featherminecraft.com

main: com.featherminecraft.RegionControl.RegionControl
depend: [WorldGuard, WorldEdit]
softdepend: [SpoutPlugin]

commands:

permissions:
