factions:
  neutralfaction:
    displayname:
    permissionsgroup:
    default: true
    
  faction1:
    displayname: 'The Elder Tyrants'
    permissionsgroup:
    default: false
    defaultspawn:
      x:
      y:
      z:
    color:
      red:
      green:
      blue:

worlds:
  world:
    regions:
      exampleregion_worldguard_id:
        world: world
        displayname: 'Example Region Name'
        baseinfluence: 300
        adjacentregions:
          - exampleregion2
          - exampleregion3
        controlpoints:
          a:
            x:
            y:
            z:
          b:
            x:
            y:
            z:
          c:
            x:
            y:
            z:
        spawnpoint:
          x:
          y:
          z:



spout:
  enabled: true
  maxspawnpoints: 10