name: RegionControl
version: "0.3-D4"
description: Utilises WorldGuard Regions to create a Capture-the-Region gamemode.
author: Jhett12321
website: http://featherminecraft.com

main: com.featherminecraft.regioncontrol.RegionControl
depend: [WorldGuard, WorldEdit]
softdepend: [SpoutPlugin]

commands:

permissions:
